"""added read state to message

Revision ID: bddcf6e21c59
Revises: 9b95a5de9df4
Create Date: 2022-05-16 17:19:08.937422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddcf6e21c59'
down_revision = '9b95a5de9df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'read')
    # ### end Alembic commands ###
